default-board:
  title: "§aBoardify"
  lines:
    - "§7Name: §e{player}"
    - "§7Online: §e{online}"
    - "§7Ping: §e{ping}ms"
    - "§7World: §e{world}"
    - "§7Pos: §eX: {x} Y: {y} Z: {z}"
    - "§7Health: §e{health}/{max_health}"
